# Generated by Django 5.2.5 on 2025-08-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_tweet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
    ]
